### ISSUE TITLE
Detail component bouwen

### ISSUE THREAD

**Issue by christoph3r3w** [Jason2426/your-tribe-for-life-squad-page#10]
- [ ] Image
- [ ] Info about person
- [ ] iframe for member socials

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by christoph3r3w** [comment]
## **Detail component design sketch**

<img width="800" src="https://github.com/user-attachments/assets/bb94de18-cb2b-4379-b57a-8a3837601cf6">
<img width="800" src="https://github.com/user-attachments/assets/2fa2f10b-63b9-453e-a48d-82374bbfaa40">
<img width="800" src="https://github.com/user-attachments/assets/7f766c7c-53f8-4738-8765-9bdf89a4e79b">
<img width="800" src="https://github.com/user-attachments/assets/a2b746de-69fe-421f-b5bb-15298f0abaf2">

<br>
<br>

**inspired by :** 

<img witdh="800" src="https://github.com/user-attachments/assets/5a2e6a8d-4b5b-4922-ba14-821205df0006">

> https://www.federicopian.com/projects/darko-bratina

<br>

## Figma
