### ISSUE TITLE
Dark / lightmode component bouwen

### ISSUE THREAD

**Issue by Daan645** [Jason2426/your-tribe-for-life-squad-page#15]
Bouw een button waarmee je tussen dark en light mode kan switchen.

**Comment by Jason2426** [comment]
## [Link to Code / Annelinde](https://github.com/Jason2426/your-tribe-for-life-squad-page/commit/4f5242b8179d8440057c39f324efe6d4bb11c674)

https://github.com/user-attachments/assets/b7fc6c8f-1a92-44cb-bf65-bb366bff8a28
