### ISSUE TITLE
Ontwerp / Inspiratie opdoen (Brainstormen)

### ISSUE THREAD

**Issue by Jason2426** [Jason2426/your-tribe-for-life-squad-page#3]
## brainstorming sessions on 03-09-24 

- [Miro Board](https://miro.com/app/board/uXjVKjp9VhE=/)
- https://www.blobmaker.app/

**Comment by TristanKatte** [comment]
Misschien een carousel plaatsen nadat je op de persoon hebt gekilkt als enhancement.
