### ISSUE TITLE
Tijdinschatting specifieker maken

### ISSUE THREAD

**Issue by suustenvoorde** [Jason2426/your-tribe-for-life-squad-page#38]
Jullie maken nu gebruik van een tijdsinschatting met een XS, S, M, L etc. Waar is deze inschatting op gebaseerd? 

Probeer dit de volgende keer in gespreksvorm met elkaar te bespreken a.d.h.v. een tool als bijvoorbeeld planningpoker. Taken die jullie aanmaken, kunnen nog kleiner en specifieker gemaakt worden.

**Comment by Jason2426** [comment]
Planning poker gebruikt voor nieuwe issues
