### ISSUE TITLE
Testen / Usertest met klasgenoten of docenten (min.3) Iteration 2

### ISSUE THREAD

**Issue by christoph3r3w** [Jason2426/your-tribe-for-life-squad-page#57]
# How to execute the tests

# Test results

# How can we solve this

**Comment by annelinderaadsheer** [comment]
Ik heb een Usertest gedaan met mijn vriend (thuis).

De informatie die ik heb gegeven is: 

- Je bent en student
- Je wilt informatie zien over de squadleden op de website

De vragen die ik tijdens de Usertest heb gesteld zijn:

- Kun je de informatie die je zoekt vinden?
- Is de website makkelijk te navigeren?

Conclusie van de Usertest:

Door de titel is duidelijk te zien dat je op de squadpage bent en door de foto's van iedereen zie je ook duidelijk dat dit om de squadleden gaat. 
Door de hover over de afbeelding is ook duidelijk te zien dat je op de persoon kan klikken voor meer informatie.
Hoewel de informatie te vinden is via klikken op de afbeeldingen, zou een zoek- of filterfunctie handig zijn, vooral als de lijst met squadleden groter wordt
