### ISSUE TITLE
Testen / Lighthouse test (voor automated performance en usability) Iteration 2

### ISSUE THREAD

**Issue by Jason2426** [Jason2426/your-tribe-for-life-squad-page#60]
# How to execute the tests
- Run the lighthouse extension in the browser.
- Test on the latest version/branch of the website.

# Test results

# How can we solve this

**Comment by Daan645** [comment]
Mobile peformance test:
Het grootste probleem is dat er 3 layout shifts zijn, er moeten standaard image sizes komen
Ook staat er dat de javascript geminimaliseerd moet worden.

![Image](https://github.com/user-attachments/assets/b94246bf-3ca3-47bd-95b4-c3499ce9af88)

**Comment by Daan645** [comment]
Desktop peformance test:
We scoren 87% volgens we moeten proberen de images in een kleiner bestand opteslaan zoals een svg, de image formaten die wij nu gebruiken zijn te zwaar, ik heb hier een issue voor rgemaakt:

**Comment by Daan645** [comment]
Toegankelijkheids test desktop: 
We scoren 84% dit komt door het volgende.

- De subtext onder de h1 heeft een te lage contrast : 
https://github.com/Jason2426/your-tribe-for-life-squad-page/issues/67

- De h elementen zijn in een onjuiste volgorde geplaatst meet the team moet h2 zijn inplaats van h3
https://github.com/Jason2426/your-tribe-for-life-squad-page/issues/68

- De pagina heeft geen title element :https://github.com/Jason2426/your-tribe-for-life-squad-page/issues/66
