### ISSUE TITLE
Testen / Browsertest (chrome, safari, firefox, edge) Iteration 2

### ISSUE THREAD

**Issue by Jason2426** [Jason2426/your-tribe-for-life-squad-page#61]
# How to execute the tests
- Check the site on browserstack or just different browsers.
- 
# Test results

# How can we solve this

**Comment by Daan645** [comment]
Ik heb getest op de volgende browsers: Arc, Chrome, firefox. Op elke browser werkte alle functies en zag alles er hetzelfde uit!
Firefox:
![Image](https://github.com/user-attachments/assets/d0b25807-5e2e-4c66-8d22-70e9506fffbf)

Chrome:
![Image](https://github.com/user-attachments/assets/374c5946-9d5f-48dc-9c4b-5762b453a83b)

Arc:
![Image](https://github.com/user-attachments/assets/e62976f4-04ee-437f-8ef0-0d18cd8c2746)
